# Generated by Django 5.2.4 on 2025-08-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, help_text='Признак, является ли здание новостройкой', null=True),
        ),
    ]
