# Generated by Django 5.2.4 on 2025-08-04 16:00

from django.db import migrations


def update_new_building_field(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")

    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [migrations.RunPython(update_new_building_field)]
