# Generated by Django 5.2.4 on 2025-08-06 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_claim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='like_by',
            field=models.ManyToManyField(related_name='likes_flats', to=settings.AUTH_USER_MODEL),
        ),
    ]
