# Generated by Django 5.2.4 on 2025-08-06 15:10

from django.db import migrations
import phonenumbers
from phonenumbers import NumberParseException


def update_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")

    for flat in Flat.objects.all().iterator(chunk_size=100):
        try:
            national_num = phonenumbers.parse(flat.owners_phonenumber, 'RU').national_number
        except NumberParseException:
            national_num = 0

        if national_num == 0:
            phone = None
        else:
            phone = f"+7{national_num}"
        flat.owner_pure_phone = phone
        flat.save()




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone_alter_flat_like_by_and_more'),
    ]

    operations = [migrations.RunPython(update_owner_pure_phone)
    ]
