# Generated by Django 5.2.4 on 2025-08-06 15:51

from django.db import migrations


def create_owners_by_flats(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(owner=flat.owner,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone)
        owner[0].flat_owned.add(flat.id)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_flat_owner_pure_phone_owner'),
    ]

    operations = [migrations.RunPython(create_owners_by_flats)
    ]
