# Generated by Django 5.2.4 on 2025-08-09 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_claim_flat_alter_claim_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='like_by',
            field=models.ManyToManyField(blank=True, related_name='flats_with_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
